# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      if: startsWith(github.ref, 'refs/tags')
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{github.ref_name}}"
         echo "Tag name from github.ref: ${{github.ref}}"
         package_version="${{github.ref_name}}"
         package_version="${package_version:1}"
         echo "Package version: ${package_version}"
         chmod +x create-nuget-package
         ./create-nuget-package ${package_version} ${{secrets.nuget_api_key}}
